name: 'Rush Cache'
description: 'Save rush build cache with Github actions'
author: 'Chamupathi Gigara Hettige'
branding:
  icon: 'database'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
